import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BookOpen, Brain, CalendarDays, ChevronRight, FileText, Flame, Gauge, GraduationCap, HardDrive, Menu, MessageSquare, Plus, RefreshCw, Save, Trash2, Trophy, Upload, X } from 'lucide-react'
import './index.css'

const API = import.meta.env.VITE_API_URL || '/api'
const LS = { notes:'sb_notes', practice:'sb_practice', plan:'sb_plan', friend:'sb_friend' }
const read = (k, fallback) => { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : fallback } catch { return fallback } }
const write = (k,v) => localStorage.setItem(k, JSON.stringify(v))

function App(){
  const [tab,setTab] = useState('home')
  const [notes,setNotes] = useState(()=>read(LS.notes,[]))
  const [practice,setPractice] = useState(()=>read(LS.practice,{attempts:0,correct:0,history:[]}))
  const [plan,setPlan] = useState(()=>read(LS.plan,[]))
  const [friend,setFriend] = useState(()=>localStorage.getItem(LS.friend)||'MY FRIEND')
  const [mobile,setMobile] = useState(false)
  useEffect(()=>write(LS.notes,notes),[notes]); useEffect(()=>write(LS.practice,practice),[practice]); useEffect(()=>write(LS.plan,plan),[plan]); useEffect(()=>localStorage.setItem(LS.friend,friend),[friend])
  const score = practice.attempts ? Math.round((practice.correct/practice.attempts)*100) : 0
  return <div className="scanlines min-h-screen">
    <header className="sticky top-0 z-40 border-b-2 border-[#765e35] bg-[#11100df2] backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4">
        <button onClick={()=>setTab('home')} className="flex items-center gap-3 text-left"><div className="grid h-11 w-11 place-items-center border-2 border-[#e5b94d] bg-[#d49a2a] text-[#17120b] shadow-[4px_4px_0_#6b421c]"><GraduationCap size={26}/></div><div><div className="pixel-title text-[11px] text-[#e5b94d]">STUDY BUDDY</div><div className="text-lg text-[#bca778]">LOCAL-FIRST // AI COMPANION</div></div></button>
        <button className="pixel-btn secondary md:hidden" onClick={()=>setMobile(!mobile)}><Menu size={18}/></button>
        <nav className={`${mobile?'flex':'hidden'} md:flex absolute md:static left-0 right-0 top-full bg-[#11100d] md:bg-transparent border-b md:border-0 border-[#765e35] p-4 md:p-0 flex-col md:flex-row gap-2`}>
          <Nav active={tab==='home'} onClick={()=>{setTab('home');setMobile(false)}} icon={<Gauge size={16}/>} text="HOME"/>
          <Nav active={tab==='notes'} onClick={()=>{setTab('notes');setMobile(false)}} icon={<FileText size={16}/>} text="NOTES"/>
          <Nav active={tab==='chat'} onClick={()=>{setTab('chat');setMobile(false)}} icon={<MessageSquare size={16}/>} text="ASK"/>
          <Nav active={tab==='practice'} onClick={()=>{setTab('practice');setMobile(false)}} icon={<Brain size={16}/>} text="PRACTICE"/>
          <Nav active={tab==='plan'} onClick={()=>{setTab('plan');setMobile(false)}} icon={<CalendarDays size={16}/>} text="PLAN"/>
        </nav>
      </div>
    </header>
    <main className="mx-auto max-w-7xl px-4 py-8">{tab==='home'&&<Home setTab={setTab} notes={notes} practice={practice} score={score} friend={friend} setFriend={setFriend}/>} {tab==='notes'&&<Notes notes={notes} setNotes={setNotes}/>} {tab==='chat'&&<Chat notes={notes}/>} {tab==='practice'&&<Practice notes={notes} practice={practice} setPractice={setPractice}/>} {tab==='plan'&&<Planner plan={plan} setPlan={setPlan} notes={notes}/>}</main>
    <footer className="mx-auto max-w-7xl px-4 pb-10 pt-4 text-center text-base text-[#76694d]">NO DATABASE // NOTES + PRACTICE LIVE IN THIS BROWSER // OPEN-WEIGHT AI</footer>
  </div>
}
function Nav({active,onClick,icon,text}){return <button onClick={onClick} className={`flex items-center gap-2 border-2 px-3 py-2 text-sm ${active?'border-[#e5b94d] bg-[#d49a2a] text-[#17120b]':'border-[#765e35] bg-[#1a1610] text-[#d9c48e]'}`}>{icon}{text}</button>}
function Home({setTab,notes,practice,score,friend,setFriend}){
  return <div className="fade-in space-y-7">
    <section className="crt-card grid gap-7 p-6 md:grid-cols-[1.4fr_.6fr] md:p-9">
      <div><span className="badge mb-4">HACKTOBERFEST // BUILD FOR A FRIEND</span><h1 className="pixel-title max-w-3xl text-2xl text-[#f0c85b] md:text-4xl">YOUR NOTES.<br/>YOUR PACE.<br/>YOUR BUDDY.</h1><p className="mt-5 max-w-2xl text-2xl leading-7 text-[#c7b58b]">A retro study desk powered by open-weight AI. Ask questions, practice from your own material, and keep your progress in your browser.</p><div className="mt-6 flex flex-wrap gap-3"><button className="pixel-btn" onClick={()=>setTab('notes')}>LOAD NOTES <ChevronRight size={18} className="inline"/></button><button className="pixel-btn secondary" onClick={()=>setTab('practice')}>START PRACTICE</button></div></div>
      <div className="border-2 border-dashed border-[#765e35] bg-[#0f0d0a] p-5"><div className="text-sm text-[#8d7c58]">STUDYING FOR</div><input className="retro-input mt-2 text-2xl" value={friend} onChange={e=>setFriend(e.target.value.toUpperCase())}/><div className="mt-6 grid grid-cols-2 gap-3"><Stat label="NOTES" value={notes.length}/><Stat label="ATTEMPTS" value={practice.attempts}/><Stat label="SCORE" value={`${score}%`}/><Stat label="STREAK" value="1 DAY"/></div></div>
    </section>
    <section className="grid gap-5 md:grid-cols-3"><Feature icon={<FileText/>} title="NOTES" text="Import PDFs or write notes. Nothing is saved on a server." onClick={()=>setTab('notes')}/><Feature icon={<MessageSquare/>} title="ASK BUDDY" text="Ask questions grounded in the material you loaded." onClick={()=>setTab('chat')}/><Feature icon={<Brain/>} title="PRACTICE" text="Generate MCQs and track your weak areas locally." onClick={()=>setTab('practice')}/></section>
    <div className="crt-card p-5 text-xl"><span className="text-[#e5b94d]">OPEN INNOVATION:</span> the app keeps notes and practice history in browser storage. AI inference uses an open-weight model through the server, so your HF secret never reaches the browser.</div>
  </div>
}
function Stat({label,value}){return <div className="border-2 border-[#4e3d23] p-3 text-center"><div className="text-2xl text-[#e5b94d]">{value}</div><div className="text-sm text-[#7e704f]">{label}</div></div>}
function Feature({icon,title,text,onClick}){return <button onClick={onClick} className="crt-card p-5 text-left transition"><div className="mb-3 flex items-center gap-3 text-[#e5b94d]">{icon}<span className="pixel-title text-sm">{title}</span></div><p className="text-xl leading-6 text-[#bca778]">{text}</p></button>}

function Notes({notes,setNotes}){
  const [title,setTitle]=useState('New note'); const [body,setBody]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
  const save=()=>{ if(!body.trim())return; setNotes([{id:crypto.randomUUID(),title:title.trim()||'Untitled',body:body.trim(),updated:new Date().toISOString()},...notes]); setTitle('New note');setBody('');setMessage('Saved locally.'); }
  const upload=async(e)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setMessage('Reading PDF...');try{const fd=new FormData();fd.append('file',file);const r=await fetch(`${API}/extract`,{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw Error(data.message);setTitle(data.title.replace(/\.pdf$/i,''));setBody(data.text);setMessage('PDF extracted. Review it, then save locally.')}catch(err){setMessage(err.message||'Could not read PDF.')}finally{setBusy(false);e.target.value=''}}
  return <div className="fade-in grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><section className="crt-card p-5"><div className="mb-4 flex items-center justify-between"><h2 className="pixel-title text-lg text-[#e5b94d]">NOTE DESK</h2><label className="pixel-btn secondary"><Upload size={16} className="inline"/> PDF<input hidden type="file" accept="application/pdf" onChange={upload}/></label></div><input className="retro-input mb-3 text-xl" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="retro-input min-h-[390px] resize-y text-xl" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write notes here or import a PDF..."/><div className="mt-3 flex items-center justify-between gap-3"><span className="text-[#887a5c]">{busy?'WORKING...':message||'Saved only when you press SAVE.'}</span><button className="pixel-btn" onClick={save}><Save size={16} className="inline"/> SAVE LOCAL</button></div></section><section className="space-y-4"><div className="flex items-end justify-between"><div><div className="text-sm text-[#806f4c]">LOCAL LIBRARY</div><h2 className="pixel-title text-xl text-[#e5b94d]">{notes.length} NOTES</h2></div>{notes.length>0&&<button className="pixel-btn secondary" onClick={()=>{if(confirm('Delete every local note?'))setNotes([])}}><Trash2 size={16}/></button>}</div>{notes.length===0?<Empty text="No notes yet. Import a PDF or write your first note."/>:notes.map(n=><article className="crt-card p-5" key={n.id}><div className="flex items-start justify-between gap-4"><div><h3 className="pixel-title text-sm text-[#f0c85b]">{n.title}</h3><p className="mt-2 text-sm text-[#776a4d]">{new Date(n.updated).toLocaleString()}</p></div><button className="text-[#9b503e]" onClick={()=>setNotes(notes.filter(x=>x.id!==n.id))}><Trash2 size={18}/></button></div><p className="mt-4 max-h-32 overflow-hidden whitespace-pre-wrap text-lg leading-6 text-[#c6b58c]">{n.body}</p></article>)}</section></div>
}

function Chat({notes}){
  const [noteId,setNoteId]=useState(notes[0]?.id||''); const [messages,setMessages]=useState([]); const [q,setQ]=useState(''); const [busy,setBusy]=useState(false); const selected=notes.find(n=>n.id===noteId); useEffect(()=>{if(!noteId&&notes[0])setNoteId(notes[0].id)},[notes,noteId])
  const ask=async()=>{if(!q.trim()||busy)return;const question=q.trim();setQ('');const next=[...messages,{role:'user',content:question}];setMessages(next);setBusy(true);try{const r=await fetch(`${API}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,context:selected?.body||'',history:next.slice(-8)})});const data=await r.json();if(!r.ok)throw Error(data.message);setMessages([...next,{role:'assistant',content:data.answer}])}catch(e){setMessages([...next,{role:'assistant',content:`SYSTEM ERROR: ${e.message}`}])}finally{setBusy(false)}}
  return <div className="fade-in grid gap-6 lg:grid-cols-[.3fr_.7fr]"><aside className="crt-card p-5"><h2 className="pixel-title text-lg text-[#e5b94d]">SOURCE</h2><p className="my-4 text-xl text-[#a79773]">Choose what Buddy should use as its study material.</p><select className="retro-input text-lg" value={noteId} onChange={e=>setNoteId(e.target.value)}><option value="">No notes</option>{notes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select>{selected&&<div className="mt-4 border-2 border-[#4e3d23] p-3 text-lg text-[#a79773]">{selected.body.length.toLocaleString()} characters loaded.</div>}</aside><section className="crt-card flex min-h-[650px] flex-col p-5"><div className="border-b-2 border-[#4e3d23] pb-4"><h2 className="pixel-title text-lg text-[#e5b94d]">ASK STUDY BUDDY</h2><p className="text-lg text-[#817354]">Answers are grounded in the selected note.</p></div><div className="flex-1 space-y-4 overflow-y-auto py-5">{messages.length===0?<div className="grid h-full place-items-center text-center text-xl text-[#716548]"><div><MessageSquare size={42} className="mx-auto mb-4 opacity-60"/><p>TRY: “Explain this topic like I'm a beginner.”</p></div></div>:messages.map((m,i)=><div key={i} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[85%] whitespace-pre-wrap border-2 p-4 text-xl leading-7 ${m.role==='user'?'border-[#a97d28] bg-[#2a2113] text-[#f0d99e]':'border-[#4e3d23] bg-[#0f0d0a] text-[#c7b78e]'}`}>{m.content}</div></div>)}{busy&&<div className="text-[#e5b94d]">BUDDY IS THINKING...</div>}</div><div className="flex gap-2"><input className="retro-input text-xl" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask about your notes..."/><button className="pixel-btn" onClick={ask} disabled={busy}>SEND</button></div></section></div>
}

function Practice({notes,practice,setPractice}){
  const [topic,setTopic]=useState(''); const [count,setCount]=useState(5); const [difficulty,setDifficulty]=useState('medium'); const [quiz,setQuiz]=useState(null); const [answers,setAnswers]=useState({}); const [loading,setLoading]=useState(false); const context=notes.map(n=>`# ${n.title}\n${n.body}`).join('\n\n');
  const generate=async()=>{if(!topic.trim())return;setLoading(true);setQuiz(null);setAnswers({});try{const r=await fetch(`${API}/quiz`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,context,count:Number(count),difficulty})});const data=await r.json();if(!r.ok)throw Error(data.message);setQuiz(data)}catch(e){alert(e.message)}finally{setLoading(false)}}
  const submit=()=>{if(!quiz)return;let correct=0;quiz.questions.forEach((x,i)=>{if(Number(answers[i])===x.answer)correct++});const attempt={id:crypto.randomUUID(),topic,score:correct,total:quiz.questions.length,at:new Date().toISOString()};setPractice(p=>({attempts:p.attempts+quiz.questions.length,correct:p.correct+correct,history:[attempt,...p.history].slice(0,12)}));setQuiz({...quiz,submitted:true,score:correct})}
  return <div className="fade-in grid gap-6 lg:grid-cols-[.32fr_.68fr]"><section className="crt-card h-fit p-5"><h2 className="pixel-title text-lg text-[#e5b94d]">PRACTICE LAB</h2><p className="my-4 text-xl text-[#a79773]">Generate questions from your local notes.</p><input className="retro-input mb-3 text-xl" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Topic: Deadlocks"/><select className="retro-input mb-3" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>easy</option><option>medium</option><option>hard</option></select><select className="retro-input mb-3" value={count} onChange={e=>setCount(e.target.value)}><option value="3">3 questions</option><option value="5">5 questions</option><option value="10">10 questions</option></select><button className="pixel-btn w-full" onClick={generate} disabled={loading}>{loading?'GENERATING...':'GENERATE QUIZ'}</button><div className="mt-6 border-t-2 border-[#4e3d23] pt-4"><div className="text-sm text-[#806f4c]">ALL-TIME ACCURACY</div><div className="mt-2 text-4xl text-[#e5b94d]">{practice.attempts?Math.round(practice.correct/practice.attempts*100):0}%</div><div className="progress-track mt-2"><div className="progress-fill" style={{width:`${practice.attempts?practice.correct/practice.attempts*100:0}%`}}/></div></div></section><section>{!quiz?<Empty text="Generate a quiz to start your practice run."/>:<div className="space-y-5">{quiz.questions.map((q,i)=><div className="crt-card p-5" key={i}><div className="badge">QUESTION {i+1}</div><h3 className="mt-3 text-2xl text-[#f0dfb1]">{q.question}</h3><div className="mt-4 grid gap-2">{q.options.map((o,j)=><label key={j} className={`border-2 p-3 text-xl ${answers[i]!==undefined&&Number(answers[i])===j?'border-[#e5b94d] bg-[#2a2113]':'border-[#4e3d23] bg-[#0f0d0a]'}`}><input className="mr-3" type="radio" name={`q${i}`} value={j} checked={Number(answers[i])===j} disabled={quiz.submitted} onChange={e=>setAnswers({...answers,[i]:e.target.value})}/>{o}</label>)}</div>{quiz.submitted&&<div className={`mt-4 border-2 p-3 ${Number(answers[i])===q.answer?'border-[#6e9b58] bg-[#1c2b17]':'border-[#9b503e] bg-[#321915]'}`}><b>{Number(answers[i])===q.answer?'CORRECT':'NOT QUITE'}</b><div>{q.explanation}</div></div>}</div>)}{!quiz.submitted?<button className="pixel-btn" onClick={submit}>CHECK ANSWERS</button>:<div className="crt-card p-5 text-2xl text-[#e5b94d]">RUN COMPLETE: {quiz.score}/{quiz.questions.length} <button className="pixel-btn secondary ml-3" onClick={generate}><RefreshCw size={16} className="inline"/> AGAIN</button></div>}</div>}</section></div>
}

function Planner({plan,setPlan,notes}){
  const [days,setDays]=useState(7); const [hours,setHours]=useState(2); const [goal,setGoal]=useState('Finish my current study notes'); const [loading,setLoading]=useState(false)
  const generate=async()=>{setLoading(true);try{const context=notes.map(n=>`# ${n.title}\n${n.body}`).join('\n\n');const prompt=`Create a practical ${days}-day study plan for this goal: ${goal}. I have ${hours} hours per day. Return ONLY JSON as an array of objects with day, focus, task, minutes. Use these notes when useful:\n${context.slice(0,10000)}`;const r=await fetch(`${API}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:prompt,context:'',history:[]})});const d=await r.json();if(!r.ok)throw Error(d.message);let raw=d.answer.replace(/```json|```/g,'').trim();const parsed=JSON.parse(raw.slice(raw.indexOf('['),raw.lastIndexOf(']')+1));setPlan(parsed.map((x,i)=>({...x,id:crypto.randomUUID(),done:false,day:x.day||i+1})));}catch(e){alert('Could not create the plan. Try again. '+e.message)}finally{setLoading(false)}}
  return <div className="fade-in grid gap-6 lg:grid-cols-[.35fr_.65fr]"><section className="crt-card p-5"><h2 className="pixel-title text-lg text-[#e5b94d]">MISSION PLANNER</h2><p className="my-4 text-xl text-[#a79773]">Make a plan and keep completion locally.</p><textarea className="retro-input mb-3 min-h-28 text-xl" value={goal} onChange={e=>setGoal(e.target.value)}/><label className="block text-[#8c7b58]">DAYS<select className="retro-input mt-1 mb-3" value={days} onChange={e=>setDays(e.target.value)}><option>3</option><option>5</option><option>7</option><option>14</option></select></label><label className="block text-[#8c7b58]">HOURS / DAY<input className="retro-input mt-1 mb-4" type="number" min="1" max="8" value={hours} onChange={e=>setHours(e.target.value)}/></label><button className="pixel-btn w-full" disabled={loading} onClick={generate}>{loading?'PLANNING...':'GENERATE PLAN'}</button></section><section>{plan.length===0?<Empty text="No mission plan yet."/>:<div className="space-y-3">{plan.map((x,i)=><label key={x.id||i} className={`crt-card flex gap-4 p-4 ${x.done?'opacity-55':''}`}><input type="checkbox" className="mt-1 h-5 w-5 accent-[#d49a2a]" checked={!!x.done} onChange={e=>setPlan(plan.map(p=>p.id===x.id?{...p,done:e.target.checked}:p))}/><div><div className="badge">DAY {x.day}</div><h3 className="mt-2 text-2xl text-[#e5b94d]">{x.focus}</h3><p className="text-xl text-[#c0af84]">{x.task}</p><span className="text-[#796a4c]">{x.minutes||hours*60} MINUTES</span></div></label>)}<button className="pixel-btn danger" onClick={()=>setPlan([])}>CLEAR PLAN</button></div>}</section></div>
}
function Empty({text}){return <div className="crt-card grid min-h-52 place-items-center p-6 text-center text-xl text-[#786a4d]">{text}</div>}

createRoot(document.getElementById('root')).render(<App />)
